import { describe, expect, test } from "bun:test";
import { ApiKeySchema, ApiKeyStatus } from "@buf/elide_cloud.bufbuild_es/elide/cloud/v1/auth_pb";
import { MembershipRole, OrgKind, OrgSchema } from "@buf/elide_cloud.bufbuild_es/elide/cloud/v1/tenancy_pb";
import { AccountStatus, UsagePeriod } from "@buf/elide_cloud.bufbuild_es/elide/cloud/v1/usage_pb";
import { create, fromBinary, fromJson, toBinary, toJson } from "@bufbuild/protobuf";
import { timestampDate, timestampFromDate } from "@bufbuild/protobuf/wkt";

/**
 * Compile-time (and round-trip) consumption point for the published `elide.cloud.v1`
 * protobuf SDK: `@buf/elide_cloud.bufbuild_es`, generated by protoc-gen-es v2 from BSR
 * module `buf.build/elide/cloud`.
 *
 * Nothing in `src/` imports the generated code yet — later tasks decide what the cloud
 * barrel exposes. This file exists so the pinned generated contract sits inside the
 * typecheck and test graph from the moment the dependency lands: if the SDK is
 * unpublished, repinned to an incompatible commit, or the wire shape of a message we
 * depend on changes, this breaks rather than a downstream client at runtime.
 */

const CREATED_AT = new Date("2026-08-01T12:00:00.000Z");

describe("elide.cloud.v1 generated SDK", () => {
	test("exposes the four protos the cloud client depends on", async () => {
		const [auth, tenancy, usage, admin] = await Promise.all([
			import("@buf/elide_cloud.bufbuild_es/elide/cloud/v1/auth_pb"),
			import("@buf/elide_cloud.bufbuild_es/elide/cloud/v1/tenancy_pb"),
			import("@buf/elide_cloud.bufbuild_es/elide/cloud/v1/usage_pb"),
			import("@buf/elide_cloud.bufbuild_es/elide/cloud/v1/admin_pb"),
		]);
		expect([
			auth.file_elide_cloud_v1_auth.name,
			tenancy.file_elide_cloud_v1_tenancy.name,
			usage.file_elide_cloud_v1_usage.name,
			admin.file_elide_cloud_v1_admin.name,
		]).toEqual(["elide/cloud/v1/auth", "elide/cloud/v1/tenancy", "elide/cloud/v1/usage", "elide/cloud/v1/admin"]);
	});

	test("schemas carry their fully-qualified proto type names", () => {
		expect(ApiKeySchema.typeName).toBe("elide.cloud.v1.ApiKey");
		expect(OrgSchema.typeName).toBe("elide.cloud.v1.Org");
	});
});

describe("ApiKey round-trip", () => {
	const key = create(ApiKeySchema, {
		id: "key_01JZ",
		orgId: "org_01JZ",
		name: "ci-runner",
		prefix: "ek_live_abcd",
		scopes: ["deploy:write", "usage:read"],
		status: ApiKeyStatus.ACTIVE,
		createdBy: "usr_01JZ",
		createdAt: timestampFromDate(CREATED_AT),
	});

	test("create() produces a tagged message with the declared fields", () => {
		expect(key.$typeName).toBe("elide.cloud.v1.ApiKey");
		expect(key.prefix).toBe("ek_live_abcd");
		expect(key.scopes).toEqual(["deploy:write", "usage:read"]);
		expect(key.status).toBe(ApiKeyStatus.ACTIVE);
		// Unset optional message fields stay undefined rather than defaulting.
		expect(key.expiresAt).toBeUndefined();
		expect(key.lastUsedAt).toBeUndefined();
	});

	test("binary encode/decode preserves every field, timestamps included", () => {
		const bytes = toBinary(ApiKeySchema, key);
		expect(bytes.byteLength).toBeGreaterThan(0);

		const decoded = fromBinary(ApiKeySchema, bytes);
		expect(decoded).toEqual(key);
		expect(decoded.scopes).toEqual(["deploy:write", "usage:read"]);
		expect(decoded.status).toBe(ApiKeyStatus.ACTIVE);
		expect(timestampDate(decoded.createdAt!)).toEqual(CREATED_AT);
	});

	test("JSON encoding uses proto3 camelCase names and enum value names", () => {
		const json = toJson(ApiKeySchema, key);
		const fields = json as Record<string, unknown>;
		expect(fields.orgId).toBe("org_01JZ");
		expect(fields.createdBy).toBe("usr_01JZ");
		expect(fields.status).toBe("API_KEY_STATUS_ACTIVE");
		expect(fields.createdAt).toBe("2026-08-01T12:00:00Z");
		// Proto3 default-valued fields are omitted, not emitted as nulls.
		expect(fields).not.toHaveProperty("expiresAt");

		expect(fromJson(ApiKeySchema, json)).toEqual(key);
	});
});

describe("Org round-trip", () => {
	test("binary and JSON forms agree for a nested-enum message", () => {
		const org = create(OrgSchema, {
			id: "org_01JZ",
			realmId: "rlm_01JZ",
			kind: OrgKind.TEAM,
			slug: "acme",
			displayName: "Acme, Inc.",
			createdAt: timestampFromDate(CREATED_AT),
		});

		expect(fromBinary(OrgSchema, toBinary(OrgSchema, org))).toEqual(org);
		const json = toJson(OrgSchema, org);
		const fields = json as Record<string, unknown>;
		expect(fields.kind).toBe("ORG_KIND_TEAM");
		expect(fields.displayName).toBe("Acme, Inc.");
		expect(fromJson(OrgSchema, json)).toEqual(org);
	});
});

describe("enum surfaces the cloud client branches on", () => {
	test("ApiKeyStatus pins its lifecycle values", () => {
		expect(ApiKeyStatus.UNSPECIFIED).toBe(0);
		expect(ApiKeyStatus.ACTIVE).toBe(1);
		expect(ApiKeyStatus.REVOKED).toBe(2);
	});

	test("tenancy enums pin org kinds and membership roles", () => {
		expect(OrgKind.PERSONAL).toBe(1);
		expect(OrgKind.TEAM).toBe(2);
		expect({
			owner: MembershipRole.OWNER,
			admin: MembershipRole.ADMIN,
			member: MembershipRole.MEMBER,
			billing: MembershipRole.BILLING,
		}).toEqual({ owner: 1, admin: 2, member: 3, billing: 4 });
	});

	test("usage enums expose account status and rollup periods", () => {
		expect({
			unspecified: AccountStatus.UNSPECIFIED,
			active: AccountStatus.ACTIVE,
			suspended: AccountStatus.SUSPENDED,
			closed: AccountStatus.CLOSED,
		}).toEqual({ unspecified: 0, active: 1, suspended: 2, closed: 3 });
		expect({
			unspecified: UsagePeriod.UNSPECIFIED,
			hour: UsagePeriod.HOUR,
			day: UsagePeriod.DAY,
			month: UsagePeriod.MONTH,
		}).toEqual({ unspecified: 0, hour: 1, day: 2, month: 3 });
	});
});
