"""Repository rule providing hermetic cmake + ninja for cargo build scripts.

audiopus_sys builds its vendored opus through the `cmake` crate, which
resolves `cmake` (and, with CMAKE_GENERATOR=Ninja, `ninja`) from the build
script's PATH. Historically that PATH pointed at host directories, which made
the build depend on whatever the runner image shipped — and broke remote
execution outright (BuildBuddy workers carry no cmake). This repo pins the
official CMake and Ninja release binaries for the exec host and exposes them
under `bin/` (cmake) and `ninja-bin/` (ninja), both of which the audiopus_sys
annotation prepends to the build-script PATH (see MODULE.bazel).

The two directories are not cosmetic. On macOS `bin/` is a symlink into the
Apple-notarized CMake.app, and writing ninja into that bundle makes macOS treat
it as tampered — the write fails and the bundle is deleted, leaving cmake to die
with SIGKILL ("damaged"). ninja therefore gets a directory of its own.

Like @llvm_msvc_tools, the archive choice keys off the *host* running the
repository rule: with remote execution the exec platform is linux-x64, so
drive RBE builds from a linux-x64 host (CI) — a darwin-hosted RBE build would
stage darwin tools onto the linux workers.
"""

_CMAKE_VERSION = "4.1.2"

# host key -> (cmake release asset suffix, sha256)
_CMAKE_DISTS = {
    "linux-x64": ("linux-x86_64", "773cc679c3a7395413bd096523f8e5d6c39f8718af4e12eb4e4195f72f35e4ab"),
    "linux-arm64": ("linux-aarch64", "0634996f918b3bab11f45522899c81c987b09c9a64d15f6a0d2bb51c42099534"),
    "macos-x64": ("macos-universal", "3be85f5b999e327b1ac7d804cbc9acd767059e9f603c42ec2765f6ab68fbd367"),
    "macos-arm64": ("macos-universal", "3be85f5b999e327b1ac7d804cbc9acd767059e9f603c42ec2765f6ab68fbd367"),
}

_NINJA_VERSION = "1.13.2"

# host key -> (ninja release asset, sha256)
_NINJA_DISTS = {
    "linux-x64": ("ninja-linux.zip", "5749cbc4e668273514150a80e387a957f933c6ed3f5f11e03fb30955e2bbead6"),
    "linux-arm64": ("ninja-linux-aarch64.zip", "fd2cacc8050a7f12a16a2e48f9e06fca5c14fc4c2bee2babb67b58be17a607fc"),
    "macos-x64": ("ninja-mac.zip", "c99048673aa765960a99cf10c6ddb9f1fad506099ff0a0e137ad8960a88f321b"),
    "macos-arm64": ("ninja-mac.zip", "c99048673aa765960a99cf10c6ddb9f1fad506099ff0a0e137ad8960a88f321b"),
}

_BUILD = """\
# Generated by //bazel/toolchains/cmake:tools.bzl — pinned CMake {cmake_version}
# + Ninja {ninja_version} for the exec host ({host}).
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "tools",
    srcs = glob(["bin/**", "ninja-bin/**", "share/**", "CMake.app/**"], allow_empty = True),
)
"""

def _host_key(rctx):
    os_name = rctx.os.name.lower()
    arch = rctx.os.arch.lower()
    if os_name.startswith("linux"):
        host_os = "linux"
    elif os_name.startswith("mac") or os_name.startswith("darwin"):
        host_os = "macos"
    else:
        fail("bazel/toolchains/cmake: unsupported exec host OS: " + rctx.os.name)
    if arch in ("amd64", "x86_64", "x64"):
        host_cpu = "x64"
    elif arch in ("aarch64", "arm64"):
        host_cpu = "arm64"
    else:
        fail("bazel/toolchains/cmake: unsupported exec host CPU: " + rctx.os.arch)
    return host_os + "-" + host_cpu

def _cmake_tools_impl(rctx):
    key = _host_key(rctx)
    cmake_suffix, cmake_sha256 = _CMAKE_DISTS[key]
    prefix = "cmake-{}-{}".format(_CMAKE_VERSION, cmake_suffix)
    rctx.report_progress("Downloading CMake {} ({})".format(_CMAKE_VERSION, cmake_suffix))
    rctx.download_and_extract(
        url = "https://github.com/Kitware/CMake/releases/download/v{}/{}.tar.gz".format(_CMAKE_VERSION, prefix),
        sha256 = cmake_sha256,
        stripPrefix = prefix,
    )

    # The macOS archive is an app bundle; surface its bin/ (cmake, and the
    # share/ data it locates relative to the binary) at the repo top level so
    # the PATH entry is the same on every host.
    #
    # CMake.app is Apple-notarized and its resources are sealed, so nothing may
    # ever be written *into* it: adding an executable to a signed bundle reads
    # as malware persistence, and macOS answers by refusing the write (EPERM)
    # and deleting the bundle outright. The symlinked bin/ then dangles, and the
    # `cmake` the audiopus_sys build script resolves from PATH either fails
    # signature validation — killed with SIGKILL, reported as "damaged" — or is
    # simply gone. That is why ninja lands in its own ninja-bin/ below rather
    # than joining cmake in bin/, and why doc/man are only pruned when they are
    # real top-level directories (linux); on macOS they live inside the bundle.
    if key.startswith("macos-"):
        rctx.symlink("CMake.app/Contents/bin", "bin")
        rctx.symlink("CMake.app/Contents/share", "share")

    # Drop the bundled GUI/docs where present; only bin/ + share/cmake-* (the
    # Modules/ tree cmake refuses to run without) matter to build scripts.
    if not key.startswith("macos-"):
        for name in ("doc", "man"):
            entry = rctx.path(name)
            if entry.exists:
                rctx.delete(entry)

    # ninja-bin/ on every host, not bin/: on macOS bin/ is the notarized bundle
    # (see above), and a uniform layout keeps the PATH annotation in MODULE.bazel
    # host-independent.
    ninja_asset, ninja_sha256 = _NINJA_DISTS[key]
    rctx.report_progress("Downloading Ninja {} ({})".format(_NINJA_VERSION, ninja_asset))
    rctx.download_and_extract(
        url = "https://github.com/ninja-build/ninja/releases/download/v{}/{}".format(_NINJA_VERSION, ninja_asset),
        sha256 = ninja_sha256,
        output = "ninja-bin",
    )

    rctx.file("BUILD.bazel", _BUILD.format(
        cmake_version = _CMAKE_VERSION,
        ninja_version = _NINJA_VERSION,
        host = key,
    ), executable = False)

    return rctx.repo_metadata(reproducible = True)

cmake_tools_repository = repository_rule(
    implementation = _cmake_tools_impl,
    doc = "Pinned CMake + Ninja release binaries for the exec host.",
)
